# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME', 'vendor']


# Site Settings
title: "DConf 2018"
email: "dconf@dlang.org"
description: "DConf is the main face-to-face event for everyone in the D programming language community and anyone who wants to know what all the fuss is about."
baseurl: "/dconf18"
url: "https://dconf.org"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "DLF"
organizerAlternateName: "D Language Foundation"
organizerDescription: "Non-profit public charity devoted to advancing open source technology related to the D programming language."
organizerEmail: "foundation@dlang.org"
organizerLogo: "/img/seo/dconf.svg"
organizerLink: "https://dlang.org/foundation"

# Head
metaKeywords: "event, conference, dconf, event, dmd, dlang, d programming language, c++, munich"
twitterAccount: "@DConf"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 #- {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "d-banner.png"
heroTitle: "DConf <typeout> 2018"
eventDate: "2.5 - 5.5 2018"
typeoutTextValues: '"", "Conference", "Munich", "Programming", "Hackathon"'
typeoutFallback: "Season"
heroButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About DConf"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "Join the main face-to-face event for everyone in the D programming language community. Awesome speakers and lots of fun!" }
 - {title: "After partys", image: "workshop.jpg", text: "Get to know other D hackers over a traditional Bavarian beer." }
 - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want to have one day to focus on your new project, PR or DIP? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "150", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure D"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from research to experience reports"}
 - {count: "3", specialCharacter: "", info: "keynotes", detail: "of experts"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Conference Hall"
eventLocationLink: "https://www.nh-hotels.com/hotel/nh-muenchen-messe"
eventStreetAddress: "Eggenfeldener Str. 100"
eventAddressLocality: "Munich"
eventAddressLocalityRegion: "Bavaria"
eventPostalCode: "81929"
eventAddressCountry: "Germany"
eventStartTime: "2018-05-02T09:00"
eventDoorTime: "09:00"
eventEndTime: "2018-05-05T20:00"
eventPlaceCoordinates: "48.13959,11.642926"
mapCenterCoordinates: "48.13959,11.642926"
mapMobileCenterCoordinates: "48.13959,11.642926"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_2.jpg"
venueSmallImage2: "venue_3.jpg"
venueSmallImage3: "venue_4.jpg"
venueTitle: "NH München Messe"
venueFeatures: ["Free WiFi", "Professional Catering", "Close to green parks"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "dconf"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Stay in touch with DConf and get the latest news."

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "340"
  priceCurrency: "USD"
  ticketsNumber: "100"
  ribbon: "-10%"
  buyButtonLink: "https://www.paypal.com/webapps/shoppingcart?flowlogging_id=7bf1d95182180&mfid=1519264869320_7bf1d95182180#/checkout/openButton"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2018-01-01T00:00"
  validThrough: "2018-03-20T23:59"
 -
  name: "Last Chance"
  price: "400"
  priceCurrency: "USD"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2018-03-21T00:00"
  validThrough: "2018-04-31T23:59"
  disabled: true
 -
  name: "Corporate"
  price: "600"
  priceCurrency: "USD"
  ticketsNumber: "100"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Support the D Language Foundation"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2018-01-01T00:00"
  validThrough: "2018-04-31T23:59"
  #soldOut: true
  #soldOutText: "Sold Out"

# Footer
socialLinks:
 #- {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=D_Programming", icon: "twitter"}
 - {link: "https://facebook.com/dlang.org", icon: "facebook"}
 #- {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://dlang.org", text: "dlang.org"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:dconf@dlang.org", text: "dconf@dlang.org"}
 #-
  #title: "FAQ"
  #links:
   #- {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "dconf"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "To be filled."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Munich"
directionDetailsCards:
 - {title: "From the Airport", information: "Take the S8 from the Munich Airport, which departs every 20 minutes, to get to the station \"Daglfing\". The hotel is located in a walking distance from about 15 minutes to reach the hotel. It's a 30 minutes trip. You can choose between a single ticket (2,80€), a day ticket (6,60€) or a ticket for a week (15,00€). Within the ticket price, you can take the train, as well as the bus in the inner circle of Munich centre."}
 - {title: "Public Transit", information: "Take the S2 towards Erding or the S4 or S6 towards Ebersbergrom. Alight at Berg am Laim (a 15 minute journey). Here, exit onto Hultschiner Straßeand and use the underpass to access Berg am Laim Bhf station. Take bus 190 towards Zamil park from here until Zamdorf Siedlung .The stop if 50 meters away from the hotel, you'll see it on the right. A zone 1 ticket is required."}
 - {title: "Hotels", information: "Like to hit the snooze button a few times before a busy day at DConf? This year, you'll be able to hit it a couple of times more than you could at past editions! DConf 2018 is taking place at the NH München Messe, a 253-room hotel in the Zamdorf area of Munich.Not only will this save you time, it will save you money. The hotel is offering a discount to DConf 2018 attendees. To take advantage of this offer and book a single room (including breakfast) for €89/night, send an email to <a href='mailto:reservierungen@nh-hotels.com'>reservierungen@nh-hotels.com</a> with the keyword D-Conf in the subject line. Visit <a href='https://www.nh-hotels.com/hotel/nh-muenchen-messe'>nh-hotels.com</a> for directions and points of interest."}
#directionDetailsWideCards:
 #-
  #title: "Questions?"
  #subCards:
   #-
    #title: "Hotels"
    #links:
     #- {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     #- {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     #- {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     #- {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   #-
    #title: "Registration"
    #links:
     #- {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     #- {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     #- {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     #- {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   #-
    #title: "Attendance Details"
    #links:
     #- {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     #- {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     #- {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     #- {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "TBA"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "TBA"}
 - {title: "Polymer", image: "hackathon-2.png", details: "TBA"}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "TBA"}
 - {title: "1nd Place", image: "prize-1.png", info: "TBA"}
 - {title: "3nd Place", image: "prize-3.png", info: "TBA"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "NH München Messe"
hackathonLocationLink: "https://www.nh-hotels.com/hotel/nh-muenchen-messe"
hackathonStreetAddress: "Eggenfeldener Str. 100"
hackathonAddressLocality: "Munich"
hackathonAddressLocalityRegion: "Bavaria"
hackathonPostalCode: "81929"
hackathonAddressCountry: "Germany"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2018-05-05T09:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2018-05-05T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "48.13959,11.642926"
hackathonMapCenterCoordinates: "48.13959,11.642926"
hackathonMapMobileCenterCoordinates: "48.13959,11.642926"
